---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rancher
  namespace: cattle-system
spec:
  interval: 30m
  chart:
    spec:
      # renovate: registryUrl=https://releases.rancher.com/server-charts/latest
      chart: rancher
      version: latest
      sourceRef:
        kind: HelmRepository
        name: rancher
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: ingress-nginx
      namespace: networking
  values:
    hostname: &host "rancher.${SECRET_DOMAIN}"
    bootstrapPassword: ${RANCHER_BOOTSTRAP_PASSWORD}
    replicas: 3
    ingress:
      enabled: true
      ingressClassName: nginx
      tls:
        source: secret
      extraAnnotations:
        external-dns.alpha.kubernetes.io/target: "ingress.${SECRET_DOMAIN}"
        hajimari.io/enable: "true"
        hajimari.io/icon: "google-home"
        hajimari.io/appName: "rancher"
