ansible_become_pass: ENC[AES256_GCM,data:e2LKrKIPHNktSI0=,iv:k/feD6x9ZMQ86LoQPkrdLX/hkGxeCvcsy8Ks7rSMtos=,tag:gxaqo5tSPk0ENFtT/HOwBQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ee463dp8xdql8l343hh7yfvljtyuq2dtlg89f2qmwx0x7thtj49sf7f6pw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkZWx0VXNQbUtxakZsUTIr
            bjhhR1Bwem5GelVxTkhzYXNKc1BBRUZHTzNFCjVISnE4T1U3RC9ybHIraCs2S1ZD
            cTVBK2ZxYm14QUhBU2wrZi9Fd3pzR28KLS0tIGwwRUluSkpNVnUxRVhpdlRJNnhk
            Z0lyVWwyRUxGQUF0NnNxRXZmTXhaVkEKhhFVNFtXdOnzREUqrAv3GXBXrwtUFfdu
            myunlEuaZ/R3jg2ct1K10fxaQqGH83Y+UDFhisl7edyw1E7lEyvVOw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-07T01:29:08Z"
    mac: ENC[AES256_GCM,data:Ig9iR3JtTDMnhxPy/nQjHbE7m7hHGpcX9oYnfxL2GXDjX+Z3vamPSuV/7ttlyQazjYKhhZbnr8QVsWGzRPwj03fzwTw/9EcSX8DQdWKX1xWU0zZ6MKbuCpRACP0ExhRug8iCQPak5PZ9H2rCU0nBffutLeW+od0J+kYtWr3LMJk=,iv:c4QwjTqOeXTqFgBao2AhuemwPCUlLB3CzqtwoF5+HPA=,tag:WChUh+Mr+7LKXBGTAxMEFA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
