ansible_become_pass: ENC[AES256_GCM,data:vCMTQPo0Za0u2Eg=,iv:9YW+kPGUKoNk0gM6HBhG1ZjHAYj+1mNL2Ct+5y3u8mU=,tag:OTtjDWMimpcRtLrdu6aeHw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ee463dp8xdql8l343hh7yfvljtyuq2dtlg89f2qmwx0x7thtj49sf7f6pw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrbDBvZzk4WEtkVno5dktE
            anY5NWUvbktaekE4VzUvdkhFT3luWGNqOVQwCnNFMEdTbmYxQ2lrdkpXS1luTzQx
            cmJkZlUzNTkzTUsrYVVwVGRMR2ZpSnMKLS0tIHFTRUVQTmhuOVdtYWlURjVCTko5
            NnQwc2FKYm5YdzNhdFZ0MkxXbDM2ZmcKaRG4JLcz2UTGqEAKjzepdQfM1CUJD9VO
            XyCnY9X4OQ6h7NIP1uwAwIpTzXbUYu9oG4K/Ff602xRWaJdxzpaWDQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-06T02:16:30Z"
    mac: ENC[AES256_GCM,data:V9F4i7/atzWnblclz7uRjrbNdFY7xNDqQH4QwuBpdO2/eWPTAnwrM07odQEuE5bkP9pCt/G3GTLxf51PUj2qUIZD/Nn3XrrvBcsofA16cxtNMjPybv+xDJRaMymppnwzdhc4XE3Cztuh77yR4IYsCqR7eamxhNAjgSbC4N/WVPQ=,iv:M2OZGyPo7DklNkaYAEre0ECPlaiIdUYNrMr3+1nrLAc=,tag:16GYsMpMGjbK4nxHlmhvFQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
