ansible_become_pass: ENC[AES256_GCM,data:czERxs0BMNKUBK8=,iv:yb/l760MRC7lVP722DuB7cYA+QeqHSm0+RWcuP3jVDc=,tag:y5S+EpwVCe08qDJCUlpKsQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ee463dp8xdql8l343hh7yfvljtyuq2dtlg89f2qmwx0x7thtj49sf7f6pw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQWDlQczk1QWRhSXJTcGxG
            ZzFOSUM1NGxjOUppS2ZKL05VelpMeUNmWWg4ClhQR1lPQmVXRFd5cjVOdHVERlJE
            OEVacnJkSGYzSHUzREt0YUZrbDhPNmsKLS0tIGtZRkQ1WDExZXZxY0pTb0F3ZENM
            ZGNlNWRXM0tFWjdGZ2MxR3VhU2dkdGcKYmE/uRsZmtpXPlYc2djik7MJj6KfimqW
            +TkUJeOrYxymCkqnq5Zjd4Ba2WD/xWae5zxOh34YesroUO5r+aXjJQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-07T01:29:09Z"
    mac: ENC[AES256_GCM,data:PUobw3Vescbo2TP/EABpPp4JKNfUhFlBAhHuph9Ad+XL2BCo8Q0KqICDC/um11m+jWDJMaJCf/AIm4T0mBXQOW9aCXmD5b3CsFgZb7o4jEnUNu9VBn9u5GET26Gg6Okpnfwccsh9w1pfUFqs76VeJloTsbj8FrA1FvbBzhq58pY=,iv:ZNdoJiiR02OvRbqbmji0PhPQxcDVwZkcsJ1J+gQhfeI=,tag:RFS8TiOp19M2dIBrQvnTTQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
