apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
stringData:
    admin-password: ENC[AES256_GCM,data:leS5MOYqrNXWHTehLoimehZlZe5nYbwe,iv:chgkkiihxhvulDWDmJmTgGbH602gYvkCR1W2EVQgJ0M=,tag:Hsk6jHzlLqaARRLRI/B4gA==,type:str]
    admin-user: ENC[AES256_GCM,data:MFa7Lng=,iv:sELjVPxJmcWI3z101OvsqTrxg4iuqB210ZfPwsjc0xY=,tag:v61RB/+rzf8EWp3ZJN/j5g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ee463dp8xdql8l343hh7yfvljtyuq2dtlg89f2qmwx0x7thtj49sf7f6pw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2cGZNV0dqZXQreGlrbFZi
            TnJscTJYU1EvMHM5V25vYW9RSUR4anVpY1dRCitPZGtoTU1OOForL0pFeWwwN0o2
            b2pDaVE2M0VMU1l2Y1VpVno1bStBVTgKLS0tIDBGUVVPMEJHRzBDdVZuOVpENVZZ
            dkFrY0gza1oyMXJ0Y3gwNmRrcnVKbUEK8T9VNKuTSSGs3XGRMZ+9vRtebwQjaWA8
            /40oNG3LkRIJrghJItO792e1ei33jB6bA7Iv6l7apYqEDOiTN7nofg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-06T02:16:29Z"
    mac: ENC[AES256_GCM,data:lBok3wSBpmwqvW2ITOqCrePfbdswZDPl/iafy4MT7Or1M0St9zZ7sWkgzCasMIzcNDlaUSe70X7YtmLf25mllwrTr8LDaaovvfX5sFTxnxQNVLzJYfE817TebfmYys2vLrSrXvJF2pnlp/kt8hLNkpocT6a2WDZ7ef+Ti7+OGzs=,iv:z1Ri/a8RlW5YR27P3UjYL+6PIdwWIx9BjRIxPG6kGWQ=,tag:2cq+SXLKLUVJ530tIHFBug==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
