---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 30m
  chart:
    spec:
      # renovate: registryUrl=https://charts.longhorn.io
      chart: longhorn
      version: 1.5.0
      sourceRef:
        kind: HelmRepository
        name: longhorn-charts
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: ingress-nginx
      namespace: networking
  values:
    env:
      TZ: "${TIMEZONE}"
    persistence:
      defaultClass: false
      defaultClassReplicaCount: 1
      reclaimPolicy: Retain
    defaultSettings:
      defaultReplicaCount: 2
      replicaAutoBalance: best-effort
      defaultDataLocality: best-effort
      # backupTarget: "${SECRET_LONGHORN_BACKUP_PATH}"
      createDefaultDiskLabeledNodes: true
      storageMinimalAvailablePercentage: 10
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts: &host "longhorn.${SECRET_DOMAIN}"
      path: /
      annotations:
        # external-dns.alpha.kubernetes.io/target: "ingress.${SECRET_DOMAIN}"
        hajimari.io/enable: "true"
        hajimari.io/icon: cow
        hajimari.io/group: storage
        hajimari.io/appName: longhorn
