apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:zqlpYs5hqDUHPnzqoPIWvWnaLyfEp6OQhY5RBfv/W0Q2ZaO1J70okA==,iv:RP4sJVbcWRhI5n3KFIUY8pH76QID4MEONTA9xwK4AGY=,tag:CMstHfX6nCpPZGq5HtmwRQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ee463dp8xdql8l343hh7yfvljtyuq2dtlg89f2qmwx0x7thtj49sf7f6pw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3dkY0UlFFd0JDVEkzdmF6
            Qng4WUp2cWEwdlRRblpqRGpEK0J6MUNRc0U4CjNGbnpkMHBBTnBGWXgrdEIxeklt
            ZjlaRDlTWXZKQ3NxVGV6UGlQY0JBT1EKLS0tIGI5YzFwTGdIYmhubk5kbWJtN21W
            cXRWTFRUWS9FcXVDY24zRlJLSm00WjgKy7NKgh+IDitzJ6TgExh547Py5RM5mNdW
            /0SEkNGqSxXngBOhcDIHKzLQttpKKPVNHkdJmS+uHCO3pGvJIu5l5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-07T01:29:07Z"
    mac: ENC[AES256_GCM,data:sfwx95j/4N0Y3EYFYgez8RXfNCj/QMY6c3ed76idaXweKdZ9Ueln43aAZ4p0LTbLPrVFQYPAgMBulxp90eNUgnNFTAphjDHGACT4x1PNdxYbszXuqxPuQLH6q4Gga5wNdcRmncMZXGIkXSZljvSOT22P476cA++hukKs4xtQBS0=,iv:mekrvphHYJdlGRnl/pSv2JWl/HASJyWMIARKiQ9rOhI=,tag:iXD3ThVRqSgK/cEQo8HGPQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
