apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    api-token: ENC[AES256_GCM,data:mJzbhSK/Z2UBSyCU1hRLgPriX+yPUgFW62ut222p+mAywabmv4tahA==,iv:apBFcZPwQ7RcPLqp7aHqEsL0ZILLyh8juqS/C0YuBYo=,tag:IR0te8Lxrw8JH0OX/DkQwA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ee463dp8xdql8l343hh7yfvljtyuq2dtlg89f2qmwx0x7thtj49sf7f6pw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTVktHSEswRWRqTjdxbmZF
            V1JzczAyaWM5ZFFySmVwOFdlb0hsWHBVTDIwClU2VE53WmJyNnV1bVpJdi9FTFNF
            U0k5MDhIMVFXUWhSa1JPQnNjY1JCdGMKLS0tIGVGdlB6ZHE5eWJxTWZtcWI0SDBV
            VGNGdGtxUEFubHg5QlNvU1ZlSFFYaUUKPhGBQJ9wx/FJb67Z5tyvENUl1vicLOLn
            3n82S3C9DizQMim8xaRN1mqN7TP6YEeLQQvssIX8+YIUk8G45Cc0kw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-07T01:29:07Z"
    mac: ENC[AES256_GCM,data:sMjtEGkQdgYwGvAYA5ogiA5W3EjG9wJWNwufaaJC5W8hJWOOY+TzYD1OjAp5bZ3HbsLLhj40gSnQbamLE9RXsFfwtPaM+hdrOSRpZfAC2A/ckMQQwtZd9NXXQshTW3aWUkpZClf4IUb5SBkBrVsRobDaKJnUTMaUKJv+s80yHt8=,iv:N35hYmVib33F+IcPJ8P6RWxGHybUIROtN5ficoK7jfI=,tag:aYRf3dSspSh+JAPmezvsRw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
