apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    api-token: ENC[AES256_GCM,data:YncaJykOycdGgp+J395W1Qytbuv6e9RgQUo3qQrohvPltkmxJDxTVg==,iv:fFWkoxW7xurXDek7ujxPwOB5R5k7T1v5ZHXeU/wuHho=,tag:3vyzslzlEeVR029o+Mk06Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ee463dp8xdql8l343hh7yfvljtyuq2dtlg89f2qmwx0x7thtj49sf7f6pw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVaGpDVUtXRUU5bXpsTk5K
            KzdzL0dXMW5ZdU4xeEF2L1JwZUFVbVo0U0hBCmx2bkdmVTN5T0d0aXAwbkc0UGt1
            Y3diRk1WZUJjdU9tTHdQdHoxNFNFQ0kKLS0tIHdnZmNPYnNDK05wN0FiNWw1Tm5T
            bmo0U0hSMDR3YWwvRFgvLzg4N3NWTncKffnCZDELavvptMQAx97s0FhnZPwDu5Tg
            65FWBMHHnHydQ/Hy0gowV7qwDGoYsEskGbACTzbI+evRCiSpKwibOA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-06T02:16:29Z"
    mac: ENC[AES256_GCM,data:WVqyffIz+xH2ZtK2Zddp5fzUE3n4xFWC6C3Ncy8nRTJ5gPHgfAIma7Zk1Ab27e6xGwe1nHXzKuS1zHgXNx0bFJ6XIuJD4O3TfeYV0e6W0G4N7sl2p9u8h0Hz2hbYg/HQ44SDggGTtnTqyNntZmCXVMFv3Z28/p0UEDcmpFltFwE=,iv:2s00nmhfrAV1IQrbXa7id34AnNKxKG4RRb4jGlfZXw4=,tag:X+STVtx1K4O6rPym4TUJxw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
