---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minecraft-vanilla
  namespace: games
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: minecraft
      version: 4.9.1
      sourceRef:
        kind: HelmRepository
        name: minecraft-server
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    # deploymentAnnotations:
    #   secret.reloader.stakater.com/reload: &secret minecraft-secret
    image:
      repository: itzg/minecraft-server
      tag: latest
    resources:
      limits:
        memory: 3000Mi
      requests:
        cpu: 1000m
        memory: 2000Mi
    securityContext:
      runAsUser: 1000
      fsGroup: 1000
    livenessProbe:
      enabled: false
    readinessProbe:
      enabled: false
    startupProbe:
      enabled: false
    extraEnv:
      TZ: "${TIMEZONE}"
      ENABLE_ROLLING_LOGS: true
    persistence:
      dataDir:
        enabled: true
        existingClaim: minecraft-data-vanilla
    minecraftServer:
      eula: true
      version: 1.20.1
      type: PAPER
      difficulty: normal
      whitelist: "funkel1989"
      ops: "funkel1989"
      pvp: true
      motd: "Kubernetes Hosted Minecraft Paper Server!!! YAY!! Welcome to FunkLand"
      worldSaveName: funkland
      viewDistance: 12
      forceReDownload: true
      rcon:
        enabled: true
        serviceType: ClusterIP
        password: ${MINECRAFT_RCON_PASSWORD}
      serviceType: LoadBalancer
      servicePort: 8123
      extraPorts:
        - name: metrics
          containerPort: 9225
          protocol: TCP
          service:
            enabled: true
            embedded: false
            type: ClusterIP
            port: 9225
          ingress:
            enabled: false
        - name: map
          containerPort: 8123
          protocol: TCP
          service:
            enabled: true
            embedded: false
            type: ClusterIP
            port: 8123
          ingress:
            ingressClassName: nginx
            enabled: true
            annotations:
              external-dns.alpha.kubernetes.io/target: "ingress.${SECRET_DOMAIN}"
              hajimari.io/appName: Minecraft-Vanilla
              hajimari.io/enable: "true"
              hajimari.io/icon: simple-icons:minecraft
              hajimari.io/group: games
            hosts:
              - host: &host "minecraft-vanilla.${SECRET_DOMAIN}"
                paths:
                  - path: /
                    pathType: Prefix
            tls:
              - hosts:
                  - *host
