---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-data-vanilla
  namespace: games
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: csi-truenas-nfs
  resources:
    requests:
      storage: 10Gi
